// EigenLayer StrategyManager — enumerate strategies and share balances.
//
// NOTE: the public `stakerStrategyList` mapping is auto-generated by Solidity as
// `stakerStrategyList(address,uint256)` (index accessor), NOT `stakerStrategyList(address)`
// returning the full array. Calling with just the staker address reverts with no data.
// Use `getDeposits` instead — it's the canonical read-all method and returns strategies +
// shares in a single call.
export const eigenStrategyManagerAbi = [
  {
    type: "function",
    name: "getDeposits",
    stateMutability: "view",
    inputs: [{ name: "staker", type: "address" }],
    outputs: [
      { name: "strategies", type: "address[]" },
      { name: "shares", type: "uint256[]" },
    ],
  },
  {
    type: "function",
    name: "depositIntoStrategy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "strategy", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const eigenStrategyAbi = [
  {
    type: "function",
    name: "underlyingToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "sharesToUnderlyingView",
    stateMutability: "view",
    inputs: [{ name: "amountShares", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
] as const;
